### ISSUE TITLE
v0.7.0 on npm can't be installed on Windows because of dependency on esbuild-darwin-arm64

### ISSUE THREAD

**Issue by seashairo** [williamlmao/chimera-ui#19]
Attempting to install via `npm i @chimera-ui/components` fails on Windows with the following error message:

```
PS [removed]> npm install @chimera-ui/components
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for esbuild-darwin-arm64@0.15.18: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  arm64
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     [removed]-debug-0.log
```

I can see in v0.7.0 on npm that there's a dependency on esbuild-darwin-arm64 that's causing the error, but I can't see the same in the source here, so I'm not sure what's going on. Installing v0.6.0 (`npm i @chimera-ui/components@0.6.0`) works.

**Comment by williamlmao** [comment]
Hey @seashairo - I would recommend using shadcnui instead. That library will receive much better support than this one will, it is very popular and has many active maintainers. I am no longer actively maintaining this one.
